name: Go test

on:
  push:
    branches: [main, "dev-*"]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  go-test:
    name: go-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Test
        run: go test ./...
